Release 2.6.0
PelionIoT/manifest-tool pull request #40
Opened 2023-11-05 10:31 UTC by jenia81

2023-11-09 10:56 UTC, jenia81 commented
@JanneKiiskila Please check the code scanning errors
The logs are only for the certificate path, not its content
And I wouldn't drop them since it helps with debugging

2023-11-09 17:32 UTC, JanneKiiskila commented on manifesttool/dev_tool/actions/init.py
> +        logger.info("imported %s to %s", origin_cert_file, dest_cert_file)
Logs only file name, not content. OK.

2023-11-09 17:33 UTC, JanneKiiskila commented on manifesttool/dev_tool/actions/init.py
> +        logger.info("imported %s to %s", origin_cert_file, dest_cert_file)
Logs only file name, not content. OK.

2023-11-09 17:33 UTC, JanneKiiskila commented on manifesttool/dev_tool/actions/init.py
> +        logger.info("created %s", cert_file)
Logs only file name, not content. OK.

2023-11-09 17:33 UTC, JanneKiiskila commented on manifesttool/mtool/actions/create.py
> +            logger.info("Running %s to sign manifest.", (" ".join(cmd)))
Logs only file name, not content. OK.

2023-11-09 17:34 UTC, JanneKiiskila commented
@jenia81 - cleared false positives with comments. Resolved comments.

2023-11-15 13:47 UTC, JanneKiiskila commented on .github/workflows/pr-checker.yml
> +    - cron: '0 0 */3 * *' # Run every 3 days
I would drop the cronjob from here.

2023-11-15 13:47 UTC, JanneKiiskila commented on .github/workflows/static-checks.yml
> +    - cron: '0 0 */3 * *' # Run every 3 days
Same here, drop the cronjob from this repo.

2023-11-15 13:49 UTC, JanneKiiskila requested changes
Let's drop the cronjobs from this repo.

2023-11-16 08:52 UTC, jenia81 commented
@JanneKiiskila dropped the cron job from the GitHub action
It's a bit tricky to add the condition to the workflow
I can add it before the steps like this:
`if: github.repository == 'PelionIoT/manifest-tool' && github.event.schedule != '0 0 */3 * *' `
But then the job will start its execution so the machine will be allocated, just the execution time will be shorter.
The only way to make sure that it won't run at all is to create a difference between the workflow files in internal and public repos

2023-11-17 11:05 UTC, JanneKiiskila approved these changes

2023-11-17 17:44 UTC, JanneKiiskila approved these changes

2023-11-17 17:58 UTC, JanneKiiskila approved these changes

2023-11-19 17:32 UTC, merged